#34 crud-operations-for-admin
mehalyna/Ch-117-Python-Project-ITA pull request #42
Opened 2021-03-25 19:00 UTC by tommyfromche

2021-03-25 19:28 UTC, SerhiiPenteliuk commented
Add new lines where necessary

2021-03-25 20:24 UTC, SerhiiPenteliuk requested changes
add new lines where necessary

2021-03-26 10:04 UTC, ivan-dubei commented on softserve/app.py
> +from bson.objectid import ObjectId
list imports in sorted order

2021-03-26 10:05 UTC, ivan-dubei commented on softserve/app.py
> +app.config['MONGO_URI'] = "mongodb://localhost:27017/softserve"
move this value into config file

2021-03-26 10:08 UTC, ivan-dubei commented on softserve/app.py
> +    try:
Do we need a bare try-exept here ? May be we may add some check for 'book' ?

2021-03-26 10:10 UTC, ivan-dubei commented on softserve/app.py
> +        except:
We may add some better exception handling.
Something like:
    except Exception as e:
        <add some message with error info here>

2021-03-26 10:13 UTC, ivan-dubei commented on softserve/app.py
> +        except:
Add better errors handling

2021-03-26 10:43 UTC, Palusha commented on softserve/app.py
> +            books_collection.update(book, {'title': title, 'author': author, 'genre': genre, 'year': year,
Use update_one() instead of update()

2021-03-26 10:46 UTC, Palusha commented on softserve/app.py
> +        books_collection.delete_one(book)
Better to use update_one() for book status instead of delete_one()

2021-03-28 15:34 UTC, SerhiiPenteliuk approved these changes

2021-03-28 19:12 UTC, ivan-dubei commented
Change application name to another one, e.g to the `book_storage`, like it is done in the neighboring pool request.

2021-03-31 09:31 UTC, mehalyna commented
non actual PR

2021-03-31 09:31 UTC, closed without merging